# Generated by Django 4.2.7 on 2023-11-27 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('list', '0001_initial')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('rating', models.IntegerField()),
                ('episodeCount', models.IntegerField()),
                ('avgEpisodeLength', models.TimeField()),
            ],
        ),
    ]
