# Generated by Django 4.2.7 on 2023-11-18 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='avgEpisodeLength',
            field=models.DurationField(),
        ),
    ]
