# Generated by Django 4.2.7 on 2023-11-27 22:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_remove_entry_avgepisodelength'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Shows',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listName', models.CharField(max_length=500)),
                ('userlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='list.userlist')),
            ],
        ),
        migrations.AddField(
            model_name='entry',
            name='shows',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='list.shows'),
            preserve_default=False,
        ),
    ]
