# Generated by Django 4.2.7 on 2023-11-28 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0006_rename_listname_shows_listname_shows_listid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shows',
            name='userlist',
        ),
        migrations.AddField(
            model_name='shows',
            name='userid',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Userlist',
        ),
    ]
