# Generated by Django 4.2.7 on 2023-12-10 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0008_rename_shows_list_rename_shows_entry_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='rating',
        ),
        migrations.AddField(
            model_name='entry',
            name='seasonCount',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
