# Generated by Django 4.2.7 on 2023-12-11 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0009_remove_entry_rating_entry_seasoncount'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='entryid',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
