# Generated by Django 4.2.7 on 2023-12-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0010_entry_entryid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField()),
                ('defaultcountry', models.CharField(max_length=500)),
            ],
        ),
    ]
