# Generated by Django 4.2.7 on 2023-12-11 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0011_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='currentEpisode',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='entry',
            name='currentSeason',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
