# Generated by Django 4.2.7 on 2023-12-11 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0012_entry_currentepisode_entry_currentseason'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='onlyEpisodes',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
