# Generated by Django 4.2.7 on 2023-12-18 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0013_entry_onlyepisodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='isTelevision',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='releaseYear',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='entry',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='currentEpisode',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='currentSeason',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='episodeCount',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='onlyEpisodes',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='entry',
            name='seasonCount',
            field=models.IntegerField(null=True),
        ),
    ]
